name: Variables Job Level

on:
   push

jobs:
    docker:
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: sanketd
          IMAGE_NAME: nginx
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker login
          env:
            DOCKER_PASSWORD: s3cUrePaSsW0rd
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

        - name: Docker Publish
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        if: github.ref == 'refs/heads/main'
        needs: [docker]
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: sanketd
          IMAGE_NAME: nginx
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 