name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v6

        - name: List and Read files
          run:  |
            echo "My first GitHub Actions Job"
            ls -ltra
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
        
        # - name: Print runner Hostname
        #   run: echo $HOSTNAME

        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md