name: Multi Job Workflow

on:
  push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cosway Program
          run: sudo apt-get install cowsay

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Sleep for 30 seconds
          run: sleep 30

    test_job2:
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: Test file Exists
          run: grep "dragon" dragon.txt

    deploy_job3:
        runs-on: ubuntu-latest
        steps:
        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: echo "Deploying...."