name: Secrets and Variables Repo Level

on:
   push

env:
   CONTAINER_REGISTRY: docker.io
   IMAGE_NAME: nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docekr build
          run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

        - name: Docker Login
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}

    deploy:
        needs: [docker]
        runs-on: ubuntu-latest
        steps:
        - name: Docker run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest