name: Timeout step & job Level

on:
  workflow_dispatch:   

env:
   CONTAINER_REGISTRY: docker.io
   IMAGE_NAME: nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

        - name: Docker Login
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}

    deploy:
        needs: [docker]
        timeout-minutes: 1
        concurrency:
          group: prod-deployment
          cancel-in-progress: false
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run 
        #   timeout-minutes: 1
          run: |
           echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
           sleep 300s


## Default Behavior

# - By default, a workflow can run for **360 minutes (6 hours)**.
# - If any step or job exceeds this limit, GitHub automatically terminates the workflow.

# Step timeout → controls one task
# Job timeout → controls full pipeline section
# Workflow timeout → fixed limit (6 hours)

# Helps prevent stuck jobs and reduces CI usage cost.