name: Workflow Filters and Activities

on:
    workflow_dispatch:
    push:
        branches:
          - main
          - '!feature/*' # ignoring pushing to any branch name starting with feature using !
        # branches-ignore:
        #     - feature/*  # features/updateImages
        #     - test/**    # test/ui/index

    pull_request:
        types:
          - opened 
          - closed
        paths-ignore: # workflow will only run when a pull request that includes a change on any file other than README.md
          - README.md
        branches:
            - main    # configure workflow to only run on pull requests that target specific branches

jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
      - name: Show Event
        run: |
          echo "This workflow ran for event: ${{ github.event_name }}"